Repository zeromicro/go-zero, pull requests merged in 2021-12, with the labels that each got.

#1283 fixes #987
  tools/goctl/api/gogen/genlogic.go
  tools/goctl/api/parser/g4/ast/service.go
  tools/goctl/api/parser/g4/test/service_test.go
Labels: feature

#1325 commit missing method for redis
  core/stores/kv/store.go
  core/stores/kv/store_test.go
  core/stores/redis/redis.go
  core/stores/redis/redis_test.go
Labels: feature

#1366 fix redis try-lock bug
  core/stores/redis/redislock.go
  core/stores/redis/redislock_test.go
Labels: enhancement

#1377 fix: [goctl bug] directive output system info missing go version
  tools/goctl/bug/env.go
Labels: bug
