Repository zeromicro/go-zero, pull requests merged in 2021-11, with the labels that each got.

#1194 feat: add rest.WithPrefix to support route prefix
  rest/server.go
  rest/server_test.go
Labels: feature

#1198 feat: rpc dial can be set with NonBlock mode
  zrpc/client.go
  zrpc/config.go
  zrpc/internal/client.go
  zrpc/internal/client_test.go
Labels: feature

#1200 Generate route with prefix
  tools/goctl/api/dartgen/gen.go
  tools/goctl/api/docgen/gen.go
  tools/goctl/api/gogen/genroutes.go
  tools/goctl/api/javagen/gen.go
  tools/goctl/api/ktgen/cmd.go
  tools/goctl/api/spec/fn.go
  tools/goctl/api/spec/spec.go
  tools/goctl/api/tsgen/gen.go
Labels: do-not-merge/hold

#1203 feat: support customizing timeout for specific route
  rest/engine.go
  rest/engine_test.go
  rest/server.go
  rest/server_test.go
  rest/types.go
Labels: feature

#1206 goctl docker command add -version
  tools/goctl/docker/docker.go
  tools/goctl/docker/template.go
  tools/goctl/goctl.go
Labels: feature

#1208 feat: ignore rest.WithPrefix on empty prefix
  tools/goctl/api/gogen/genroutes.go
Labels: enhancement

#1262 Fix issue 1260
  readme-cn.md
  readme.md
  tools/goctl/api/gogen/genroutes.go
Labels: enhancement
