Repository zeromicro/go-zero, pull requests merged in 2022-04, with the labels that each got.

#1747 feat(goctl): supports api multi-level importing
  tools/goctl/api/parser/g4/ast/apiparser.go
  tools/goctl/api/parser/g4/ast/apiparser_test.go
  tools/goctl/api/parser/g4/ast/importstack.go
Labels: feature

#1775 feat: add httpc.Do & httpc.Service.Do
  core/mapping/marshaler.go
  core/mapping/marshaler_test.go
  core/mapping/unmarshaler.go
  rest/httpc/requests.go
  rest/httpc/requests_test.go
  rest/httpc/service.go
  rest/httpc/service_test.go
  rest/httpc/vars.go
Labels: feature

#1678 show help when running goctl api without any flags
  tools/goctl/api/apigen/gen.go
Labels: need-more-discussion

#1799 feat: add trace in redis & mon & sql
  core/stores/mon/collection.go
  core/stores/mon/model.go
  core/stores/mon/model_test.go
  core/stores/redis/hook.go
  core/stores/redis/hook_test.go
  core/stores/sqlx/sqlconn.go
  core/stores/sqlx/tx.go
Labels: feature

#1820 feat: upgrade grpc to 1.46
  go.mod
  go.sum
  zrpc/internal/client.go
Labels: enhancement
