Repository zeromicro/go-zero, pull requests merged in 2023-10, with the labels that each got.

#3658 feat: model add withSession
  tools/goctl/model/sql/template/tpl/model-new.tpl
  tools/goctl/model/sql/template/tpl/model.tpl
Labels: area/orm

#3662 chore: update restful/grpc servers shutdown stages
  rest/internal/starter.go
  zrpc/internal/rpcserver.go
  zrpc/internal/rpcserver_test.go
Labels: area/restful, area/grpc

#2742 feat: support the specified timeout of rpc methods
  zrpc/client.go
  zrpc/client_test.go
  zrpc/config.go
  zrpc/internal/clientinterceptors/timeoutinterceptor.go
  zrpc/internal/clientinterceptors/timeoutinterceptor_test.go
  zrpc/internal/config.go
  zrpc/internal/serverinterceptors/timeoutinterceptor.go
  zrpc/internal/serverinterceptors/timeoutinterceptor_test.go
  zrpc/server.go
  zrpc/server_test.go
Labels: area/grpc

#3680 Enhanced the CODE_OF_CONDUCT Guidelines
  code-of-conduct.md
Labels: area/documentation, kind/need-more-discussion
