Repository zeromicro/go-zero, pull requests merged in 2025-05, with the labels that each got.

#4822 chore: update goctl version
  tools/goctl/internal/version/version.go
Labels: enhancement, area/goctl

#4820 feat: add http to http method test case
  gateway/server_test.go
Labels: enhancement, testing

#4816 Fix the issue of generating swagger @doc "xxx" that fails, and use th…
  tools/goctl/api/swagger/annotation.go
  tools/goctl/api/swagger/path.go
Labels: area/documentation, lgtm, bug

#4790 fix(marshaler): fix bug when marshal array
  core/mapping/marshaler.go
  core/mapping/marshaler_test.go
Labels: bug

#4741 feat:add cache prefix support to pg
  tools/goctl/internal/flags/default_en.json
  tools/goctl/model/cmd.go
  tools/goctl/model/sql/command/command.go
Labels: area/goctl, area/orm

#4788 fix: pg gen model missing cache prefix
  tools/goctl/model/sql/command/command.go
Labels: lgtm, area/orm, bug

#4827 fix: allow special characters like periods in API route paths
  tools/goctl/pkg/parser/api/parser/parser.go
  tools/goctl/pkg/parser/api/parser/parser_test.go
Labels: enhancement, area/api

#4828 feat: improve mcp
  mcp/config.go
  mcp/config_test.go
  mcp/integration_test.go
  mcp/parser.go
  mcp/parser_test.go
  mcp/readme.md
  mcp/server.go
  mcp/server_test.go
  mcp/types.go
  mcp/types_test.go
  mcp/util.go
  mcp/util_test.go
  mcp/vars.go
  mcp/vars_test.go
Labels: feature

#4849 goctl features of 1.8.4-alpha
  tools/goctl/.gitignore
  tools/goctl/api/cmd.go
  tools/goctl/api/gogen/gen.go
  tools/goctl/api/gogen/gentypes.go
  tools/goctl/api/swagger/annotation.go
  tools/goctl/api/swagger/annotation_test.go
  tools/goctl/api/swagger/command.go
  tools/goctl/api/swagger/const.go
  tools/goctl/api/swagger/contenttype.go
  tools/goctl/api/swagger/contenttype_test.go
  tools/goctl/api/swagger/context.go
  tools/goctl/api/swagger/definition.go
  tools/goctl/api/swagger/example/example.api
  tools/goctl/api/swagger/example/example.swagger.json
  tools/goctl/api/swagger/example/example_cn.api
  tools/goctl/api/swagger/example/example_cn.swagger.json
  tools/goctl/api/swagger/options.go
  tools/goctl/api/swagger/options_test.go
  tools/goctl/api/swagger/parameter.go
  tools/goctl/api/swagger/path.go
  tools/goctl/api/swagger/properties.go
  tools/goctl/api/swagger/response.go
  tools/goctl/api/swagger/swagger.go
  tools/goctl/api/swagger/swagger_test.go
  tools/goctl/build.env
  tools/goctl/build.sh
  tools/goctl/internal/flags/default_en.json
  tools/goctl/internal/version/version.go
  tools/goctl/pkg/parser/api/parser/parser.go
  tools/goctl/pkg/parser/api/parser/parser_test.go
  tools/goctl/pkg/parser/api/parser/testdata/info_test.api
  tools/goctl/pkg/parser/api/parser/testdata/test.api
Labels: enhancement, feature, area/goctl
